[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  SECRETS_SCAN_ENABLED = "false"
  SECRETS_SCAN_OMIT_KEYS = "VITE_SUPABASE_URL,VITE_SUPABASE_ANON_KEY,VITE_OPENAI_API_KEY,PORT,NODE_ENV,SUPABASE_URL"

# セキュリティスキャンを無効化
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# セキュリティスキャン設定
[build.processing.secrets]
  enabled = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[headers]
  # Security headers
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

  # Cache static assets
  for = "/assets/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

  # Cache images
  for = "*.png"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

  for = "*.jpg"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

  for = "*.jpeg"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

  for = "*.gif"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

  for = "*.svg"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

  for = "*.webp"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 